# Generated by Django 3.2.15 on 2022-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='region2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.CharField(max_length=100)),
                ('regionName', models.CharField(max_length=500)),
            ],
        ),
    ]
