# Generated by Django 3.2.15 on 2022-08-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region2',
            options={'managed': False},
        ),
    ]
