# Generated by Django 3.2.15 on 2022-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_gas', '0002_alter_region2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.IntegerField(db_column='regionId', primary_key=True, serialize=False)),
                ('regionname', models.CharField(db_column='regionName', max_length=45)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='region2',
        ),
    ]
